### ISSUE TITLE
Infrequent vertical text in newly achieved achievement

### ISSUE THREAD

**Issue by goldfndr** [streetcomplete/StreetComplete#2330]
Sometimes an achievement will display the text as vertical along the right margin of the icon instead of below the icon. See these screenshots:
 
![Capture+_2020-11-19-18-18-32](https://user-images.githubusercontent.com/173956/100686671-ac2e5b80-3333-11eb-8251-98bf8a8b442f.png)
![Capture+_2020-11-26-01-31-44](https://user-images.githubusercontent.com/173956/100686683-b2bcd300-3333-11eb-83d1-7fb48defabb9.png)

I recall seeing at least a third, older instance, but didn't capture it. Most of the time the text is below the icon. I took care to make sure for the second image above that my device (LG V50, resolution 3120x1440) was stably in portrait mode (not transitioning from landscape due to rotation).

**Versions affected**
These both occurred in v27.0-beta2.

**Comment by goldfndr** [comment]
I've today seen the bug with a High-Rise achievement via version v27.1. I'd previously gotten Surveyor 12 correctly oriented. It seems to occur more often if I have one new achievement instead of two new achievements, but that might be coincidence.

**Comment by peternewman** [comment]
I've not personally seen it on my device, even when having two achievements stacked up. Currently v27.0beta3.

**Comment by westnordost** [comment]
> Currently v27.0beta3.

Why are you not using v27.1 by the way?

**Comment by westnordost** [comment]
The layout for the achievement info dialog is also defined for landscape layout:
![image](https://user-images.githubusercontent.com/4661658/101176472-d55a2f00-3646-11eb-90b9-2a73257a9a90.png)

So for some reason your smartphone decided that it would be a good idea to use the landscape layout in portrait mode.

**Comment by peternewman** [comment]
> Why are you not using v27.1 by the way?

Just hadn't got round to upgrading, I have now.

**Comment by westnordost** [comment]
Ok I think I solved it. The layout was created only once on startup and then never replaced. So if you had your smartphone on landscape on startup and then later rotated it into portrait, the achivements would look like that.

**Comment by westnordost** [comment]
There is a regression. Sometimes, the app crashes now. I haven't found out why. I did "something", let's see if the crash vanishes in v28.0-beta2.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.westnordost.streetcomplete/de.westnordost.streetcomplete.MainActivity}: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class fragment
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3122)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6923)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
Caused by: android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class fragment
Caused by: java.lang.IllegalStateException: Fragment de.westnordost.streetcomplete.notifications.NotificationsContainerFragment did not create a view.
at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:139)
at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:780)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
at de.westnordost.streetcomplete.MainActivity.onCreate(MainActivity.java:136)
at android.app.Activity.performCreate(Activity.java:7148)
at android.app.Activity.performCreate(Activity.java:7139)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6923)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by peternewman** [comment]
I know I'm at n-1 again, but I've just played around with this in v28.0-beta2, if I open the app, then rotate it into landscape, then go into my profile it forces the app back into portrait.

Or perhaps this is unrelated and you're just talking about the new achievement pop-up, although I assumed the pop-up would be similar in both?

**Comment by westnordost** [comment]
n-1?

> if I open the app, then rotate it into landscape, then go into my profile it forces the app back into portrait.

This is deliberate.

> Or perhaps this is unrelated and you're just talking about the new achievement pop-up

Yes

**Comment by peternewman** [comment]
> n-1?

Not the latest release (i.e. the beta not the release).

> > if I open the app, then rotate it into landscape, then go into my profile it forces the app back into portrait.
> 
> This is deliberate.

Ah, because there's no layout presumably?

> > Or perhaps this is unrelated and you're just talking about the new achievement pop-up
> 
> Yes

Okay, ignore me then! :smile:

**Comment by westnordost** [comment]
Doesn't occur anymore.
