### ISSUE TITLE
Discarding envelope opening message crashes the app

### ISSUE THREAD

**Issue by Etua** [streetcomplete/StreetComplete#2451]
**How to Reproduce**
Click an area around an opening envelope animation representing OSM message. StreetComplete crashes immediately.

`Thread: main
App version: 28.0
Device: Sony XQ-AU52, Android 10
Locale: pl_PL
Stack trace:
java.lang.NullPointerException: speechbubbleContentContainer must not be null
at de.westnordost.streetcomplete.notifications.OsmUnreadMessagesFragment$startAnimation$2$1.run(OsmUnreadMessagesFragment.kt:116)
at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1074)
at android.animation.Animator$AnimatorListener.onAnimationStart(Animator.java:538)
at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1023)
at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1272)
at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1463)
at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1027)
at android.view.Choreographer.doCallbacks(Choreographer.java:852)
at android.view.Choreographer.doFrame(Choreographer.java:783)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:359)
at android.app.ActivityThread.main(ActivityThread.java:7407)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)`

**Comment by westnordost** [comment]
Can reproduce
