### ISSUE TITLE
App crashes on fast zoom with one finger

### ISSUE THREAD

**Issue by mkotzjan** [streetcomplete/StreetComplete#2601]
I'm able to crash the app by zooming in and out quickly using only one finger. I know that this is rather unusual behavior, i just discovered this by accident. See also the attached video

**How to Reproduce**
- Open StreetComplete 
- Double tap the map and hold on the second tap
- move finger up or down for zooming in or out with just one finger
- move finger quickly up and down to crash app

https://user-images.githubusercontent.com/8384904/108630360-b0ff3900-7464-11eb-8912-188182e9d040.mp4

**Versions affected**

StreetComplete v30.1
Huawei P10 Lite
Android 8.0.0

**Comment by riQQ** [comment]
I can reproduce it with StreetComplete on a Nokia 2.2 with Android 10.

```
Thread: main
App version: 30.0
Device: Nokia  WSP_sprout, Android 10
Locale: de_DE
Stack trace:
java.lang.IllegalArgumentException: Latitude NaN, Longitude NaN is not a valid position.
at de.westnordost.osmapi.map.data.LatLons.checkValidity(LatLons.java:21)
at de.westnordost.osmapi.map.data.OsmLatLon.<init>(OsmLatLon.java:23)
at de.westnordost.streetcomplete.map.tangram.CameraPosition.<init>(CameraManager.kt:225)
at de.westnordost.streetcomplete.map.tangram.CameraManager.getCamera(CameraManager.kt:61)
at de.westnordost.streetcomplete.map.tangram.KtMapController.getCameraPosition(KtMapController.kt:152)
at de.westnordost.streetcomplete.map.MapFragment.getCameraPosition(MapFragment.kt:348)
at de.westnordost.streetcomplete.map.MapFragment$registerResponders$1.onMapIsChanging(MapFragment.kt:195)
at de.westnordost.streetcomplete.map.tangram.KtMapController$6$onRegionIsChanging$1.run(KtMapController.kt:112)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7386)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
```

**Comment by smichel17** [comment]
Same for v30.0 from F-Droid on Android 7.0

**Comment by westnordost** [comment]
That's great! So finally, we have some way to reproduce it!

It is a long-standing bug in tangram-es that somehow got worse in the new tangram-es release.

I'll leave this open because maybe I should add a try-catch there to workaround the issue.

**Comment by mkotzjan** [comment]
The underlying issue in tangram-es just got closed. Thank you for connecting the dots ☺️🙏
