### ISSUE TITLE
[v32.0-alpha] crash when disabling all quests

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2784]
When clicking `reset` or `deselect all` in quests lists, the app crashes.

Built [April 20th](https://github.com/streetcomplete/StreetComplete/tree/bb71ae91976ce4f16c22c7ce09ecdcc388a649e1), but looks like no commits since then touch the involved parts.
Only modification from my side is change of package name and `fileprovider_authority` so I can have a separate testing install.

<details>
 <summary>log</summary>

```
Thread: DefaultDispatcher-worker-5
App version: 32.0-alpha1
Device: samsung serranods, Android 9
Locale: en_GB
Stack trace:
android.view.ViewRootImpl$CalledFromWrongThreadException: Only the 
original thread that created a view hierarchy can touch its views.
 at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7757)
 at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1222)
 at android.view.View.requestLayout(View.java:23114)
 at android.view.View.requestLayout(View.java:23114)
 at android.view.View.requestLayout(View.java:23114)
 at android.view.View.requestLayout(View.java:23114)
 at android.view.View.requestLayout(View.java:23114)
 at android.view.View.requestLayout(View.java:23114)
 at android.view.View.requestLayout(View.java:23114)
 at android.view.View.requestLayout(View.java:23114)
 at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:360)
 at android.view.View.requestLayout(View.java:23114)
 at 
androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
 at 
androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:5706)
 at 
androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:12653)
 at 
androidx.recyclerview.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:7584)
 at 
de.westnordost.streetcomplete.view.ListAdapter.setList(ListAdapter.kt:13)
 at 
de.westnordost.streetcomplete.settings.questselection.QuestSelectionFragment$onReset$1.invokeSuspend(QuestSelectionFragment.kt:95)
 at 
kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
 at 
kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
 at 
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
 at 
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
 at 
kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
</details>

**Comment by matkoniecz** [comment]
For me both work, but disabling all exists quests list. And resetting to default crashes app after it resets it to default.

**Comment by Helium314** [comment]
Well... yes, it is working as in setting the correct values.
But there is the crash right after doing so.

**Comment by matkoniecz** [comment]
Oh it is definitely it is a bug. Just mentioning it as potentially useful info for debugging.

**Comment by Helium314** [comment]
As indicated by the log, `onDeselectAll()` and `onReset()` not running on UI thread is the problem.
Works when I put `questSelectionAdapter.list = createQuestTypeVisibilityList()` inside some `acivitity?.runOnUiThread {}`

**Comment by Helium314** [comment]
Probably `createQuestTypeVisibilityList()` could still be called from other thread, to have something like
```
    private fun onReset() {
        lifecycleScope.launch(Dispatchers.IO) {
            questTypeOrderList.clear()
            visibleQuestTypeController.clear()
            val visibilityList = createQuestTypeVisibilityList()
            acivitity?.runOnUiThread {
                questSelectionAdapter.list = visibilityList
            }
        }
    }
```

**Comment by westnordost** [comment]
Thank you for the report, @Helium314 !
