### ISSUE TITLE
[v32.0-alpha] crash at opening hours quest

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#2830]
When entering opening hours until midnight (00:00) I get a crash:

```
j$.time.DateTimeException: Invalid value for SecondOfDay (valid values 0 - 86399): 86400
at j$.time.temporal.v.b(Unknown Source:13)
at j$.time.temporal.j.V(:2)
at j$.time.LocalTime.ofSecondOfDay(Unknown Source:2)
at de.westnordost.streetcomplete.quests.opening_hours.model.TimeRange.timeOfDayToString(TimeRange.kt:47)
at de.westnordost.streetcomplete.quests.opening_hours.model.TimeRange.toStringUsing(TimeRange.kt:38)
at de.westnordost.streetcomplete.quests.opening_hours.adapter.RegularOpeningHoursAdapter$WeekdayViewHolder.update(RegularOpeningHoursAdapter.kt:245)
```
This seems to be new, with my old build from a few days ago there is no crash.

**Comment by westnordost** [comment]
Hmpf, "24:00" is even in the ISO-8601 standard but nobody supports this...

https://stackoverflow.com/questions/31106357/simpledateformat-that-allow-240000-and-000000-as-inputs

I'll try a workaround...
