### ISSUE TITLE
Various Exceptions due to intermittent WiFi

### ISSUE THREAD

**Issue by peternewman** [streetcomplete/StreetComplete#2937]
I assume the following are all due to intermittent WiFi, rather than bugs as such in SC, but it would be nice if a toast just appeared rather than letting you email an exception.

It seems I can't combine HTML and GFM, so here's a todo list with status, then the detailed logs below:

- [x] de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443 - "already fixed"
- [ ] de.westnordost.streetcomplete.data.osmnotes.ImageActivationException:
- [ ] de.westnordost.streetcomplete.data.osmnotes.ImageUploadException: Upload failed
- [ ] de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname

<details>
<summary>de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443</summary>

at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:202)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:148)
at de.westnordost.osmapi.user.UserApi.get(UserApi.java:44)
at de.westnordost.streetcomplete.data.osmnotes.AvatarsDownloader.download(AvatarsDownloader.kt:27)
at de.westnordost.streetcomplete.data.osmnotes.AvatarsInNotesUpdater.onUpdated(AvatarsInNotesUpdater.kt:12)
at de.westnordost.streetcomplete.data.osmnotes.NoteController.onUpdated(NoteController.kt:107)
at de.westnordost.streetcomplete.data.osmnotes.NoteController.onUpdated$default(NoteController.kt:104)
at de.westnordost.streetcomplete.data.osmnotes.NoteController.put(NoteController.kt:69)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdit(NoteEditsUploader.kt:73)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.access$uploadEdit(NoteEditsUploader.kt:13)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invokeSuspend(NoteEditsUploader.kt:53)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdits(NoteEditsUploader.kt:53)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(NoteEditsUploader.kt:33)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Suppressed: de.westnordost.streetcomplete.data.download.ConnectionException: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getWay(MapDataApiImpl.kt:119)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.fetchElement(ElementEditUploader.kt:35)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.upload(ElementEditUploader.kt:20)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.uploadEdit(ElementEditsUploader.kt:44)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1$1.invokeSuspend(ElementEditsUploader.kt:35)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(ElementEditsUploader.kt:35)
... 6 more
Caused by: de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:202)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:148)
at de.westnordost.osmapi.map.MapDataApi.getOneElement(MapDataApi.java:289)
at de.westnordost.osmapi.map.MapDataApi.getWay(MapDataApi.java:271)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getWay(MapDataApiImpl.kt:85)
... 15 more
Caused by: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:341)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
... 19 more
Caused by: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:341)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
... 22 more
</details>

<details>
<summary>de.westnordost.streetcomplete.data.osmnotes.ImageActivationException:</summary>
at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.activate(StreetCompleteImageUploader.kt:84)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadMissedImageActivations$2.invokeSuspend(NoteEditsUploader.kt:41)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadMissedImageActivations$2.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadMissedImageActivations(NoteEditsUploader.kt:40)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(NoteEditsUploader.kt:31)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Suppressed: de.westnordost.streetcomplete.data.download.ConnectionException: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getWay(MapDataApiImpl.kt:119)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.fetchElement(ElementEditUploader.kt:35)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.upload(ElementEditUploader.kt:20)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.uploadEdit(ElementEditsUploader.kt:44)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1$1.invokeSuspend(ElementEditsUploader.kt:35)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(ElementEditsUploader.kt:35)
... 6 more
Caused by: de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:202)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:148)
at de.westnordost.osmapi.map.MapDataApi.getOneElement(MapDataApi.java:289)
at de.westnordost.osmapi.map.MapDataApi.getWay(MapDataApi.java:271)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getWay(MapDataApiImpl.kt:85)
... 15 more
Caused by: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
at java.net.InetAddress.getAllByName(InetAddress.java:1154)
at com.android.okhttp.Dns$1.lookup(Dns.java:39)
at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:341)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
... 19 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
... 37 more
Caused by: java.net.UnknownHostException: Unable to resolve host "westnordost.de": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
at java.net.InetAddress.getAllByName(InetAddress.java:1154)
at com.android.okhttp.Dns$1.lookup(Dns.java:39)
at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.activate(StreetCompleteImageUploader.kt:71)
... 13 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
... 30 more
</details>

<details>
<summary>de.westnordost.streetcomplete.data.osmnotes.ImageUploadException: Upload failed</summary>
at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.upload(StreetCompleteImageUploader.kt:57)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadAndGetAttachedPhotosText(NoteEditsUploader.kt:101)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdit(NoteEditsUploader.kt:58)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.access$uploadEdit(NoteEditsUploader.kt:13)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invokeSuspend(NoteEditsUploader.kt:53)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdits(NoteEditsUploader.kt:53)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(NoteEditsUploader.kt:33)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Suppressed: de.westnordost.streetcomplete.data.download.ConnectionException: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getNode(MapDataApiImpl.kt:119)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.fetchElement(ElementEditUploader.kt:34)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.upload(ElementEditUploader.kt:20)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.uploadEdit(ElementEditsUploader.kt:44)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1$1.invokeSuspend(ElementEditsUploader.kt:35)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1$1.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(ElementEditsUploader.kt:35)
... 6 more
Caused by: de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:202)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:148)
at de.westnordost.osmapi.map.MapDataApi.getOneElement(MapDataApi.java:289)
at de.westnordost.osmapi.map.MapDataApi.getNode(MapDataApi.java:262)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getNode(MapDataApiImpl.kt:81)
... 15 more
Caused by: java.net.ConnectException: Failed to connect to api.openstreetmap.org/130.117.76.11:443
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:341)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
... 19 more
Caused by: java.net.ConnectException: Failed to connect to westnordost.de/62.108.32.100:443
at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:143)
at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.upload(StreetCompleteImageUploader.kt:35)
... 16 more
</details>

<details>
<summary>de.westnordost.osmapi.common.errors.OsmConnectionException: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname</summary>
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:202)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:148)
at de.westnordost.osmapi.user.UserApi.get(UserApi.java:44)
at de.westnordost.streetcomplete.data.osmnotes.AvatarsDownloader.download(AvatarsDownloader.kt:27)
at de.westnordost.streetcomplete.data.osmnotes.AvatarsInNotesUpdater.onUpdated(AvatarsInNotesUpdater.kt:12)
at de.westnordost.streetcomplete.data.osmnotes.NoteController.onUpdated(NoteController.kt:107)
at de.westnordost.streetcomplete.data.osmnotes.NoteController.putAllForBBox(NoteController.kt:51)
at de.westnordost.streetcomplete.data.osmnotes.NotesDownloader$download$2.invokeSuspend(NotesDownloader.kt:32)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Suppressed: de.westnordost.streetcomplete.data.download.ConnectionException: javax.net.ssl.SSLException: Read error: ssl=0x7aa60ebd88: I/O error during system call, Software caused connection abort
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getMap(MapDataApiImpl.kt:119)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataDownloader.getMapAndHandleTooBigQuery(MapDataDownloader.kt:39)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataDownloader.access$getMapAndHandleTooBigQuery(MapDataDownloader.kt:15)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataDownloader$download$2.invokeSuspend(MapDataDownloader.kt:24)
... 6 more
Caused by: de.westnordost.osmapi.common.errors.OsmConnectionException: javax.net.ssl.SSLException: Read error: ssl=0x7aa60ebd88: I/O error during system call, Software caused connection abort
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:202)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:148)
at de.westnordost.osmapi.map.MapDataApi.getMap(MapDataApi.java:220)
at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.getMap(MapDataApiImpl.kt:56)
... 9 more
Caused by: javax.net.ssl.SSLException: Read error: ssl=0x7aa60ebd88: I/O error during system call, Software caused connection abort
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
at com.android.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:439)
at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:50)
at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
at com.android.okhttp.okio.InflaterSource.refill(InflaterSource.java:101)
at com.android.okhttp.okio.InflaterSource.read(InflaterSource.java:62)
at com.android.okhttp.okio.GzipSource.read(GzipSource.java:80)
at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:347)
at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
at java.io.InputStreamReader.read(InputStreamReader.java:184)
at org.kxml2.io.KXmlParser.fillBuffer(KXmlParser.java:1535)
at org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1371)
at org.kxml2.io.KXmlParser.parseStartTag(KXmlParser.java:1137)
at org.kxml2.io.KXmlParser.next(KXmlParser.java:380)
at org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
at de.westnordost.osmapi.common.XmlParser.doParse(XmlParser.java:53)
at de.westnordost.osmapi.map.MapDataParser.parse(MapDataParser.java:56)
at de.westnordost.osmapi.map.MapDataParser.parse(MapDataParser.java:20)
at de.westnordost.osmapi.OsmConnection.handleResponse(OsmConnection.java:320)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:197)
... 12 more
Caused by: java.net.UnknownHostException: Unable to resolve host "api.openstreetmap.org": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
at java.net.InetAddress.getAllByName(InetAddress.java:1154)
at com.android.okhttp.Dns$1.lookup(Dns.java:39)
at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:26)
at de.westnordost.osmapi.OsmConnection.handleResponseCode(OsmConnection.java:341)
at de.westnordost.osmapi.OsmConnection.makeRequest(OsmConnection.java:195)
... 13 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
... 31 more
</details>

**How to Reproduce**
Use SC while walking in and out of WiFi

**Versions affected**
SC v32.0

Possibly related #2912

**Comment by peternewman** [comment]
I'm assuming from:
https://github.com/streetcomplete/StreetComplete/blob/c225404d6184e337839f06f47af4ed94aef74478/app/src/main/java/de/westnordost/streetcomplete/data/osm/mapdata/MapDataApiImpl.kt#L118-L119

That the other/any OsmConnectionException will be caught in the same way so the last one is also fixed?

**Comment by westnordost** [comment]
I am pretty sure that you mixed together some exceptions into one. In any case, some or all of those have been fixed in v32.1. If one or several of them still occur in v32.1, better open a new ticket

**Comment by peternewman** [comment]
They generated separate and distinct alert dialogues and allowed me to send separate email messages to you about each one.

I don't see anything in the code that does anything other than throwing ImageActivationException or ImageUploadException, although I see there's a OsmConnectionException buried in both those stack traces, so I'll let you know if it happens again when Google choose to release the app from it's jail.
