### ISSUE TITLE
Image Upload activation failure makes upload fail with error

### ISSUE THREAD

**Issue by westnordost** [streetcomplete/StreetComplete#2984]
If the image upload activation fails due to a connection error, just a message should be displayed to the user that upload is currently not possible, it should not treat it as an application error and prompt the user to send a crash report.

Crash report:
```
de.westnordost.streetcomplete.data.osmnotes.ImageActivationException:
at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.activate(StreetCompleteImageUploader.kt:84)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadMissedImageActivations$2.invokeSuspend(NoteEditsUploader.kt:41)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadMissedImageActivations$2.invoke(Unknown Source:10)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadMissedImageActivations(NoteEditsUploader.kt:40)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(NoteEditsUploader.kt:31)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: java.net.UnknownHostException: Unable to resolve host "westnordost.de": No address associated with hostname
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
at java.net.InetAddress.getAllByName(InetAddress.java:1154)
at com.android.okhttp.Dns$1.lookup(Dns.java:39)
at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.activate(StreetCompleteImageUploader.kt:71)
... 13 more
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
at libcore.io.Linux.android_getaddrinfo(Native Method)
at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
... 30 more

```

**Comment by westnordost** [comment]
Different stacktrace, same error:

```
de.westnordost.streetcomplete.data.osmnotes.ImageUploadException: Upload failed
	at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.upload(StreetCompleteImageUploader.kt:57)
	at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadAndGetAttachedPhotosText(NoteEditsUploader.kt:101)
	at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdit(NoteEditsUploader.kt:58)
	at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.access$uploadEdit(NoteEditsUploader.kt:13)
	at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invokeSuspend(NoteEditsUploader.kt:53)
	at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invoke(Unknown Source:10)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:91)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
	at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdits(NoteEditsUploader.kt:53)
	at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$upload$$inlined$withLock$lambda$1.invokeSuspend(NoteEditsUploader.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: javax.net.ssl.SSLException: Read error: ssl=0x7220484b08: I/O error during system call, Connection reset by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
	at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:411)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:549)
	at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
	at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
	at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at de.westnordost.streetcomplete.data.osmnotes.StreetCompleteImageUploader.upload(StreetCompleteImageUploader.kt:41)
	... 16 more
```

**Comment by peternewman** [comment]
That'll be the remains of #2937 then...
