### ISSUE TITLE
StreetComplete devel version crashes on ShowQuestForms / Note

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3144]
Devel build contains useful Debug section, with `Show Quest Forms` which in nice for debugging what quest forms do, and checking translations etc. However, clicking on  `Can you contribute anything to this note?` crashes. [Most](https://github.com/streetcomplete/StreetComplete/issues/3145) of the others forms work ok.

**How to Reproduce**
- build and install devel version of StreetComplete
- go to `menu` / `Settings` / `Debug/Show Quest Forms`
- click on `Can you contribute anything to this note?`
- SC crashes with
```
Thread: main
App version: 33.2
Device: HUAWEI  HWVOG, Android 10
Locale: en_HR
Stack trace:
java.lang.ClassCastException: de.westnordost.streetcomplete.data.quest.OsmQuestKey cannot be cast to de.westnordost.streetcomplete.data.quest.OsmNoteQuestKey
        at de.westnordost.streetcomplete.quests.note_discussion.NoteDiscussionForm.onViewCreated(NoteDiscussionForm.kt:70)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
```

**Versions affected**
v33.2-devel (with [few patches](https://github.com/mnalis/StreetComplete/releases/tag/v33.2-mnalis-questprofiles-helium314) which should be unrelated)

**Comment by matkoniecz** [comment]
Note that it is a debug feature and crashes are possible there are not very problematic (though patches fixing this are welcomed).

Especially note quest is less interesting there as it may be easily triggered manually.

Main use for that feature is that one can test interface (say, when doing accessibility testing) without hunting for matching quest object with Overpass.

**Comment by westnordost** [comment]
Won't fix
