### ISSUE TITLE
StreetComplete devel version crashes on ShowQuestForms / "Is this a one way street?"

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#3146]
Devel build contains useful Debug section, with `Show Quest Forms` which in nice for debugging what quest forms do, and checking translations etc. However, clicking on  `Is this a one way street?` crashes. [Most](https://github.com/streetcomplete/StreetComplete/issues/3145) of the others forms, including similarly named form `Is this a one way street? In which direction?`, works ok. 

**How to Reproduce**
- build and install devel version of StreetComplete
- go to `menu` / `Settings` / `Debug/Show Quest Forms`
- click on `Is this a one way street?`
- SC crashes with
```
Thread: main
App version: 33.2
Device: HUAWEI  HWVOG, Android 10
Locale: en_HR
Stack trace:
java.lang.NullPointerException
        at de.westnordost.streetcomplete.quests.oneway_suspects.AddSuspectedOnewayForm$onViewCreated$1$isForward$1.invokeSuspend(AddSuspectedOnewayForm.kt:42)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Versions affected**
v33.2-devel (with [few patches](https://github.com/mnalis/StreetComplete/releases/tag/v33.2-mnalis-questprofiles-helium314) which should be unrelated)

**Comment by matkoniecz** [comment]
Like  #3144 - this is a debug feature provided with no expectation of crashlessness (and useful anyway)

This oneway quest is special and expecting special data from a different source and may be not handled.

Here I am pretty sure that it was always crashing.

**Comment by westnordost** [comment]
Won't fix

**Comment by mnalis** [comment]
Oh, ok, sure. That's why I indicated that it is in debug version. Feel free to close. 

Background: I was going through all quests to verify that https://github.com/streetcomplete/StreetComplete/issues/2643 works in all cases, so I found those 3 issues that crash. Glad to know it is unrelated.
