### ISSUE TITLE
app crash on speedbump question

### ISSUE THREAD

**Issue by Worty** [streetcomplete/StreetComplete#3261]
**How to Reproduce**
App crashes by clicking on a still exists question where ```traffic_calming=bump```

**Versions affected**
Android 10
Version 34.0 from Play Store

**Log**
```
09-05 17:26:58.224 31791 31791 D AndroidRuntime: Shutting down VM
09-05 17:26:58.224 31791 31791 E AndroidRuntime: FATAL EXCEPTION: main
09-05 17:26:58.224 31791 31791 E AndroidRuntime: Process: de.westnordost.streetcomplete, PID: 31791
09-05 17:26:58.224 31791 31791 E AndroidRuntime: java.util.MissingFormatArgumentException: Format specifier '%s'
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at java.util.Formatter.format(Formatter.java:2523)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at java.util.Formatter.format(Formatter.java:2459)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at java.lang.String.format(String.java:2911)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at android.content.res.Resources.getString(Resources.java:485)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at de.westnordost.streetcomplete.quests.QuestUtilKt.getHtmlQuestTitle(QuestUtil.kt:28)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at de.westnordost.streetcomplete.quests.AbstractQuestAnswerFragment.onViewCreated(AbstractQuestAnswerFragment.kt:162)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at de.westnordost.streetcomplete.quests.AYesNoQuestAnswerFragment.onViewCreated(AYesNoQuestAnswerFragment.kt:15)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:883)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:241)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7617)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-05 17:26:58.224 31791 31791 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
09-05 17:26:58.248 31791 31791 I Process : Sending signal. PID: 31791 SIG: 9
09-05 17:26:58.389  4077  4077 I Zygote  : Process 31791 exited due to signal 9 (Killed)
```

**Comment by westnordost** [comment]
Which language do you use on your phone?

**Comment by peternewman** [comment]
I see this on British English too, hence my bug report earlier today via Google.

**Comment by Worty** [comment]
> 
> 
> Which language do you use on your phone?

German

**Comment by westnordost** [comment]
Can you tell me the location at which this happened?

**Comment by peternewman** [comment]
I think mine would have been this or similar @westnordost a table not a speed bump:
https://www.openstreetmap.org/node/1414732239

**Comment by Worty** [comment]
My log is from this one:
https://www.openstreetmap.org/node/1071130083


![photo_2021-09-06_11-43-47](https://user-images.githubusercontent.com/6840978/132196895-9ed81194-9a65-4bc1-9549-59e288f31802.jpg)

Also crashed on this bump:
https://www.openstreetmap.org/node/3339933368

**Comment by peternewman** [comment]
Thanks @westnordost .
