### ISSUE TITLE
Crash when creating notes on ESRI background

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3306]
When creating a note via long click with aerial image background enabled the app crashes.

I know this is a (currently) disabled feature, but I report anyway because I have the impression that the technical part besides download for offline use is considered done.

Reproduced using my smoothness quest build, so no wacky modifications from my side.
Preferences xml file was manipulated to enable aerial background.
(can't test on current master because it's throwing tons of build errors, sorry if it is already fixed there)

<details>
  <summary>Log</summary>

```
Thread: main
App version: 34.0
Device: samsung serranovelte, Android 9
Locale: en_GB
Stack trace:
de.westnordost.streetcomplete.map.tangram.LoadSceneException: scene update path not found
at de.westnordost.streetcomplete.map.tangram.KtMapControllerKt.toException(KtMapController.kt:362)
at de.westnordost.streetcomplete.map.tangram.KtMapControllerKt.access$toException(KtMapController.kt:1)
at de.westnordost.streetcomplete.map.tangram.KtMapController._init_$lambda-0(KtMapController.kt:65)
at de.westnordost.streetcomplete.map.tangram.KtMapController.lambda$Bq4Dpp7zu-6-cr6v3_0B738-Wm0(Unknown Source:0)
at de.westnordost.streetcomplete.map.tangram.-$$Lambda$KtMapController$Bq4Dpp7zu-6-cr6v3_0B738-Wm0.onSceneReady(Unknown Source:2)
at com.mapzen.tangram.MapController$9.run(MapController.java:1214)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
</details>

**Comment by westnordost** [comment]
I added your comment to the PR
