### ISSUE TITLE
Crash during first scan after install

### ISSUE THREAD

**Issue by Helium314** [streetcomplete/StreetComplete#3314]
I just had a crash that happened right after installing the app, during the initial scan for quests.

After the crash, the theme was set to dark, initial start was using light theme.

So I suspect that the automatic switch from light to dark somehow triggered this crash.

Thread: main
App version: 34.0 (exact version: my current smoothness branch, https://github.com/Helium314/StreetComplete/tree/smoothness)
Device: samsung serranods, Android 9 (Lineage OS 16.0)
Locale: en_GB
Stack trace:
java.lang.RuntimeException: Unable to pause activity {de.westnordost.streetcomplete/de.westnordost.streetcomplete.MainActivity}: java.lang.RuntimeException: Failed to call observer method
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4069)
at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4024)
at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4793)
at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4732)
at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4782)
at android.app.ActivityThread.access$3200(ActivityThread.java:200)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.RuntimeException: Failed to call observer method
at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:37)
at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
at androidx.lifecycle.LifecycleRegistry.backwardPass(LifecycleRegistry.java:284)
at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:302)
at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:68)
at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:144)
at androidx.lifecycle.ReportFragment.onPause(ReportFragment.java:122)
at android.app.Fragment.performPause(Fragment.java:2723)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1353)
at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
at android.app.FragmentManagerImpl.dispatchPause(FragmentManager.java:3012)
at android.app.FragmentController.dispatchPause(FragmentController.java:215)
at android.app.Activity.performPause(Activity.java:7335)
at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1465)
at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4059)
... 16 more
Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.westnordost.streetcomplete.data.quest.QuestAutoSyncer$connectivityReceiver$1@6673b24
at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1271)
at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1504)
at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:659)
at de.westnordost.streetcomplete.data.quest.QuestAutoSyncer.onPause(QuestAutoSyncer.kt:132)
at java.lang.reflect.Method.invoke(Native Method)
at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
... 37 more

**Comment by westnordost** [comment]
So, the Android system wanted to pause a Fragment but was unable to complete this.
It was unable to, because an exception happened in the `onPause` callback in `QuestAutoSyncer`.
`QuestAutoSyncer` wanted to unregister itself in that method from any updates regarding connectivity (to the internet), but in fact, it was not registered yet.

Firstly, it's bullshit that the Android system throws an exception if you unregister but you weren't registered in the first place. 

But anyway, the only way this can happen is if `onPause` is called before `onResume` or `onResume` is not called at all. I'd say, this is undocumented behavior, so a bug at Android, not this app.

**Comment by westnordost** [comment]
So, if this happened more often, I'd probably wrap this line in a try-catch (or create a utility function that does that) but as long as it happens very rarely, I'd not go through the effort to be honest. Not so nice to litter the code with workarounds. 
I get "a lot" of crash reports like these where I quickly find out that pretty sure this is some Android issue, I don't really want to deal with this but hope they'll fix it some time. (Not really "a lot", it's always single reports. Real bugs usually accumulate more than 1 crash report)

**Comment by westnordost** [comment]
By the way, do you also see this? First time i see this, is this new or a bug (that I see it myself at least)

![image](https://user-images.githubusercontent.com/4661658/134426528-7b782a0c-92e0-40ff-8950-f3fdc0999ce0.png)

**Comment by Helium314** [comment]
Thanks for the explanation!
So I'll just close this.

> By the way, do you also see this? First time i see this, is this new or a bug (that I see it myself at least)

No, not shown for me

**Comment by westnordost** [comment]
> No, not shown for me

Lol, that makes no sense :-D
