### ISSUE TITLE
immediate crash when opening cycle path segregation quest 

### ISSUE THREAD

**Issue by timothywashere** [streetcomplete/StreetComplete#3504]
Tapping on this quest immediately crashes the app.
Restarted phone and same happens
Using Google Pixel 3 with Android 12
Based in UK

**How to Reproduce**
Tap on quest for cycle path segregation

![Screenshot_20211113-164854](https://user-images.githubusercontent.com/87654968/141652101-07379f6f-b9d5-4a66-b275-7beaf75a2ee2.png)

**Versions affected**
V37.1

**Comment by Szuwax** [comment]
I've got the same problem. Android 11, app version:37.1 (f-droid)

**Comment by matkoniecz** [comment]
reproduced, have not checked is it already fixed in development version but I see nothing in logs.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 13768
    kotlin.UninitializedPropertyAccessException: lateinit property elementGeometry has not been initialized
        at de.westnordost.streetcomplete.quests.AbstractQuestAnswerFragment.getElementGeometry(AbstractQuestAnswerFragment.kt:81)
        at de.westnordost.streetcomplete.quests.AbstractQuestAnswerFragment.get_countryInfo(AbstractQuestAnswerFragment.kt:70)
        at de.westnordost.streetcomplete.quests.AbstractQuestAnswerFragment.getCountryInfo(AbstractQuestAnswerFragment.kt:75)
        at de.westnordost.streetcomplete.quests.segregated.AddCyclewaySegregationForm.getItems(AddCyclewaySegregationForm.kt:13)
        at de.westnordost.streetcomplete.quests.AImageListQuestAnswerFragment.onAttach(AImageListQuestAnswerFragment.kt:54)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
        at androidx.fragment.app.FragmentStateManager.attach(FragmentStateManager.java:464)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:275)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by cyclingcat** [comment]
The same on my devices with Android 8.1 and Android 9: SC 37.1 crashes with a strack trace similar to the one mentioned above.

Just checked SC v37.0: No crash happens, both the quest itself and the upload of the answer work as they should.

The cycling cat

**Comment by 10992-osm** [comment]
I'm not sure whether it's worth opening another issue, but I've also had this occur with the "What can be left here for recycling?" quest on e.g. [node 5233478941](https://osm.org/node/5233478941), version 37.1, Android 12.  The best information I can provide is below, unfortunately I don't know how to access the logs as copyable text, so some screenshots will have to do.

![Screenshot 1](https://user-images.githubusercontent.com/83511672/141689811-bc59e080-9ff9-429f-9d90-c84630f2c90f.png)
![Screenshot 2](https://user-images.githubusercontent.com/83511672/141689813-58c2e8b7-4de5-4ed4-8dbe-6fff480b6156.png)
![Screenshot 3](https://user-images.githubusercontent.com/83511672/141689814-ab807c7b-fbdc-4a24-b53e-0e2f5d34e114.png)

I haven't check thoroughly, though the stack trace appears to be the same as or very similar to the one posted by @matkoniecz.

**Comment by tsievert** [comment]
Can reproduce on v37.1, Android 10. Location Finland
Same issue with quests with the football (soccer) icon

**Comment by CachingFoX** [comment]
Could be the same reason: https://github.com/streetcomplete/StreetComplete/issues/3506

**Comment by CachingFoX** [comment]
How can I see the crash log?

**Comment by 10992-osm** [comment]
> How can I see the crash log?

I'm not sure what the official way is to do it, but mine is as follows:

1. Select the quest that crashes SC.
2. SC crashes.
3. Re-open SC.
4. Select the same quest again.
5. This then seems to trigger some process in Android about repeat crashes.  I see a dialogue box that says "StreetComplete keeps stopping", which gives three buttons: "App info", "Close app" and "Send feedback".
6. Click "Send feedback".
7. Write feedback if you want, tick or untick the "Include system data" checkbox.
8. **Do not press "Send" yet.**
9. Press "Preview".
10. You can now see the logs, some of which need to be expanded by clicking on the arrow next to the title.
11. If you want to, you can now return to the main feedback page, and press "Send".

This gives you something like what I saw in the screenshots I put in my earlier comment.  I think there must be a better way to access logs, but I don't know it.

On a side note, does @westnordost get the feedback that is submitted through this method?

**Comment by Strubbl** [comment]
> On a side note, does @westnordost get the feedback that is submitted through this method?

Yes, it should be visible in the Google Play console for him. 

I just reported the same crash and found this issue here.

**Comment by CachingFoX** [comment]
> > How can I see the crash log?
> 
> I'm not sure what the official way to do it is, but mine is as follows:
> 
>     1. Select the quest that crashes SC.
> 
>     2. SC crashes.
> 
>     3. Re-open SC.
> 
>     4. Select the same quest again.
> 
>     5. This then seems to trigger some process in Android about repeat crashes.  I see a dialogue box that says "StreetComplete keeps stopping", which gives three buttons: "App info", "Close app" and "Send feedback".
> 
>     6. Click "Send feedback".
> 
>     7. Write feedback if you want, tick or untick the "Include system data" checkbox.
> 
>     8. **Do not press "Send" yet.**
> 
>     9. Press "Preview".
> 
>     10. You can now see the logs, some of which need to be expanded by clicking on the arrow next to the title.
> 
>     11. If you want to, you can now return to the main feedback page, and press "Send".
> 
> 
> This gives you something like what I saw in the screenshots I put in my earlier comment. I think there must be a better way to access logs, but I don't know it.
> 
> On a side note, does @westnordost get the feedback that is submitted through this method?

Thank you for the answer. I can repeat your tests. I don't get any dialog box after the crash(es).

I have Android 10 on a HUAWEI Mate 10 Pro.
