### ISSUE TITLE
Changing language within app reliably crashes it

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#3517]
Language change works well, but crashes app on doing it. following

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 7364
    java.lang.IllegalStateException: Can't access the Fragment View's LifecycleOwner when getView() is null i.e., before onCreateView() or after onDestroyView()
        at androidx.fragment.app.Fragment.getViewLifecycleOwner(Fragment.java:361)
        at de.westnordost.streetcomplete.ktx.FragmentKt.getViewLifecycleScope(Fragment.kt:21)
        at de.westnordost.streetcomplete.map.MainFragment.onLocationChanged(MainFragment.kt:588)
        at de.westnordost.streetcomplete.map.MainFragment.access$onLocationChanged(MainFragment.kt:71)
        at de.westnordost.streetcomplete.map.MainFragment$onAttach$1.invoke(MainFragment.kt:145)
        at de.westnordost.streetcomplete.map.MainFragment$onAttach$1.invoke(MainFragment.kt:145)
        at de.westnordost.streetcomplete.location.FineLocationManager.currentLocationConsumer$lambda-0(FineLocationManager.kt:24)
        at de.westnordost.streetcomplete.location.FineLocationManager.lambda$T74gODXXRSYBZ20d7ZuE4M_ySSE(Unknown Source:0)
        at de.westnordost.streetcomplete.location.-$$Lambda$FineLocationManager$T74gODXXRSYBZ20d7ZuE4M_ySSE.accept(Unknown Source:4)
        at androidx.core.location.LocationManagerCompat$1.run(LocationManagerCompat.java:162)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

or 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 6713
    java.lang.RuntimeException: Tried to perform an operation on an invalid pointer! This means you may have used a MapData that has already been removed.
        at com.mapzen.tangram.MapData.checkPointer(MapData.java:116)
        at com.mapzen.tangram.MapData.clear(MapData.java:108)
        at de.westnordost.streetcomplete.map.components.TracksMapComponent.putAllTracksInOldLayer(TracksMapComponent.kt:58)
        at de.westnordost.streetcomplete.map.components.TracksMapComponent.startNewTrack(TracksMapComponent.kt:47)
        at de.westnordost.streetcomplete.map.LocationAwareMapFragment.addTrackLocation(LocationAwareMapFragment.kt:203)
        at de.westnordost.streetcomplete.map.LocationAwareMapFragment.onLocationChanged(LocationAwareMapFragment.kt:188)
        at de.westnordost.streetcomplete.map.LocationAwareMapFragment.access$onLocationChanged(LocationAwareMapFragment.kt:26)
        at de.westnordost.streetcomplete.map.LocationAwareMapFragment$onAttach$2.invoke(LocationAwareMapFragment.kt:85)
        at de.westnordost.streetcomplete.map.LocationAwareMapFragment$onAttach$2.invoke(LocationAwareMapFragment.kt:85)
        at de.westnordost.streetcomplete.location.FineLocationManager$locationListener$1.onLocationChanged(FineLocationManager.kt:37)
        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:352)
        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:275)
        at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:298)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

are examples that I got in emulator

**Comment by westnordost** [comment]
When does it crash? Immediately?

The first crash actually occurs since a little time already according to the crash reports I am getting. I am pretty sure it is caused by https://github.com/streetcomplete/StreetComplete/commit/86dcf5babf823a48b926b9044ef4853a2415d71f (didn't bisect it) but I couldn't pinpoint why though... does the cancellationsignal stuff not work at all?

**Comment by matkoniecz** [comment]
> When does it crash? Immediately?

I have failed to notice any delay.

**Comment by RubenKelevra** [comment]
Hm had a crash too. I got English US as System language but had chosen German.

After exiting the settings dialog the app showed the map as a short flash and then crashed.

But since the first crash it haven't occurred again.

Despite that choosing the language won't actually do anything - the only string I found which gets translated is "Abort" as a button.

Changing the language seems to initiate a full GUI refresh with about 10 seconds delay.

It will blank everything to white and redraw the GUI elements. Despite doing this the app does not translate anything in the process.

After the crash I deleted all the app data, which might be related. I haven't had a crash since then.

**Comment by westnordost** [comment]
> Despite that choosing the language won't actually do anything - the only string I found which gets translated is "Abort" as a button.

Do you have any details?

Here is what is being done on changing the language:
- The settings screen is restarted. All strings should immediately be in the selected language
- When any other screen that has been started before is revisited (such as the main screen), it will also be restarted
That's where the "flashes" come from.

**Comment by westnordost** [comment]
So I have (very likely) found the issue for the crash and fixed it.

If there are any more issues with the language-change (which was by the way unrelated to the crash but could indirectly trigger it), please let me know in a new issue. Please also report your Android version + device in that case.
