### ISSUE TITLE
Tapping off unread message notification before it's loaded crashes the app

### ISSUE THREAD

**Issue by arrival-spring** [streetcomplete/StreetComplete#3522]
Using v38 beta 1

I have an unread message on my OSM account so when I open SC I have a notification.

If I tap on the notification, wait for the animation to finish and then tap off it then it disappears.

If I tap on the notification but tap off it while the animation is still happening then the app crashes.

<details>
<summary>Here is the stack trace from the crash report (there's no obvious way to select this as text).</summary>

![Screenshot (20 Nov 2021 14_45_07)](https://user-images.githubusercontent.com/77166354/142775220-9998150e-16f1-4678-a1da-17074cc5acfa.png)
</details>

I can reliably reproduce this, so let me know if you need more info.

**Comment by westnordost** [comment]
```
2021-11-23 17:18:15.151 31636-31636/de.westnordost.streetcomplete.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete.debug, PID: 31636
    java.lang.IllegalStateException: Fragment OsmUnreadMessagesFragment{6cc40e1} (492b58c0-86ff-4c07-8f3b-b39441f3f1a5) did not return a View from onCreateView() or this was called before onCreateView().
        at androidx.fragment.app.Fragment.requireView(Fragment.java:1964)
        at de.westnordost.streetcomplete.ktx.FragmentViewBindingPropertyDelegate.getValue(ViewBinder.kt:83)
        at de.westnordost.streetcomplete.notifications.OsmUnreadMessagesFragment.getBinding(OsmUnreadMessagesFragment.kt:29)
        at de.westnordost.streetcomplete.notifications.OsmUnreadMessagesFragment.startAnimation$lambda-6(OsmUnreadMessagesFragment.kt:91)
        at de.westnordost.streetcomplete.notifications.OsmUnreadMessagesFragment.lambda$ihdzuWyqoDdgQoygqz_76hOcALU(Unknown Source:0)
        at de.westnordost.streetcomplete.notifications.-$$Lambda$OsmUnreadMessagesFragment$ihdzuWyqoDdgQoygqz_76hOcALU.run(Unknown Source:2)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationEnd(ViewPropertyAnimator.java:1116)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1250)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1492)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1008)
        at android.view.Choreographer.doCallbacks(Choreographer.java:809)
        at android.view.Choreographer.doFrame(Choreographer.java:740)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```
