### ISSUE TITLE
Crash on switching back to StreetComplete with opened Lanes quest form

### ISSUE THREAD

**Issue by riQQ** [streetcomplete/StreetComplete#3590]
**How to Reproduce**
Open the Lanes quest, select Marked lanes and 2 lanes. Leave the dialog showing the car animations open. Switch to another app for some seconds. Switch back to StreetComplete -> crash.

Thread: main
App version: 38.1
Device: Nokia  WSP_sprout, Android 11
Locale: en_US
Stack trace:
```
java.lang.IllegalStateException: Fragment AddLanesForm{6050690} (f39ec3c4-bc01-464e-93de-cf6b14cfaad4 id=0x7f0901a8 tag=bottom_sheet) did not return a View from onCreateView() or this was called before onCreateView().
at androidx.fragment.app.Fragment.requireView(Fragment.java:1964)
at de.westnordost.streetcomplete.ktx.FragmentViewBindingPropertyDelegate.getValue(ViewBinder.kt:83)
at de.westnordost.streetcomplete.quests.AbstractQuestFormAnswerFragment.getBinding(AbstractQuestFormAnswerFragment.kt:17)
at de.westnordost.streetcomplete.quests.AbstractQuestFormAnswerFragment.checkIsFormComplete(AbstractQuestFormAnswerFragment.kt:34)
at de.westnordost.streetcomplete.quests.lanes.AddLanesForm.updatePuzzleView(AddLanesForm.kt:214)
at de.westnordost.streetcomplete.quests.lanes.AddLanesForm.setStreetSideLayout(AddLanesForm.kt:209)
at de.westnordost.streetcomplete.quests.lanes.AddLanesForm.onCreateView(AddLanesForm.kt:77)
at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3065)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2988)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
at de.westnordost.streetcomplete.MainActivity.onStart(MainActivity.kt:129)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
at android.app.Activity.performStart(Activity.java:8024)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3517)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2105)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7700)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
```

**Versions affected**
StreetComplete 38.1 on Android 11 on a Nokia 2.2

**Comment by westnordost** [comment]
Thank you! It looks like the housenumber and the max height form had the same issue.
