### ISSUE TITLE
App Crashes when Open a News Goal/archievement and screen is rotated

### ISSUE THREAD

**Issue by tursics** [streetcomplete/StreetComplete#3622]
**How to Reproduce**

* navigate to the main map
* tap on the icon for new Goal/archivement
* the animation for the nice goal image appears
* rotate the device at the same time
* the app is closed immediately

**Versions affected**
Android 10, 191215.002
StreetComplete 38.2

**Comment by westnordost** [comment]
Can reproduce. The crash is

```
    java.lang.IllegalStateException: Fragment AchievementInfoFragment{42b2ccb} (894b75c0-3d19-487d-8cd9-df50a2551453) did not return a View from onCreateView() or this was called before onCreateView().
        at androidx.fragment.app.Fragment.requireView(Fragment.java:2008)
        at de.westnordost.streetcomplete.ktx.FragmentViewBindingPropertyDelegate.getValue(ViewBinder.kt:83)
        at de.westnordost.streetcomplete.user.AchievementInfoFragment.getBinding(AchievementInfoFragment.kt:49)
        at de.westnordost.streetcomplete.user.AchievementInfoFragment.createDialogPopInAnimations$lambda-10$lambda-9(AchievementInfoFragment.kt:299)
        at de.westnordost.streetcomplete.user.AchievementInfoFragment.$r8$lambda$4jzryPxwqyrFuROStleH9ZlY1B4(Unknown Source:0)
        at de.westnordost.streetcomplete.user.AchievementInfoFragment$$ExternalSyntheticLambda2.run(Unknown Source:6)
        at android.view.ViewPropertyAnimator$AnimatorEventListener.onAnimationStart(ViewPropertyAnimator.java:1075)
        at android.animation.Animator$AnimatorListener.onAnimationStart(Animator.java:539)
        at android.animation.ValueAnimator.notifyStartListeners(ValueAnimator.java:1031)
        at android.animation.ValueAnimator.startAnimation(ValueAnimator.java:1280)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1471)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1061)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:775)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1048)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
```
