### ISSUE TITLE
GPX descriptions can only contain 255 characters

### ISSUE THREAD

**Issue by jcgruenhage** [streetcomplete/StreetComplete#4195]
**How to Reproduce**
- record track
- enter long description
- upload fails

**Expected Behavior**
There's multiple options IMO:
 - the app could provide a way to edit this description after the fact, which would help me to rescue the currently stuck GPX.
 - the app should prevent you from entering too many characters in the description

**Versions affected**

Android 11, StreetComplete 0.44.1/0.45.0

**Comment by jcgruenhage** [comment]
Stacktrace from the upload failure:

```
java.lang.IllegalArgumentException: Description must have less than 256 characters.
at de.westnordost.osmapi.traces.GpsTracesApi.checkFieldLength(GpsTracesApi.java:118)
at de.westnordost.osmapi.traces.GpsTracesApi.create(GpsTracesApi.java:53)
at de.westnordost.streetcomplete.data.osmtracks.TracksApiImpl.create(TracksApiImpl.kt:45)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadAndGetAttachedTrackText(NoteEditsUploader.kt:128)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdit(NoteEditsUploader.kt:71)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.access$uploadEdit(NoteEditsUploader.kt:23)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invokeSuspend(NoteEditsUploader.kt:64)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invoke(Unknown Source:8)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$uploadEdits$2.invoke(Unknown Source:4)
at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:1)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.uploadEdits(NoteEditsUploader.kt:64)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader.access$uploadEdits(NoteEditsUploader.kt:23)
at de.westnordost.streetcomplete.data.osmnotes.edits.NoteEditsUploader$upload$2$1.invokeSuspend(NoteEditsUploader.kt:44)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by kmpoppe** [comment]
To be exact: `Description must have less than 256 characters.` means the same as when osm.org nags about the maximum length being 25**5** characters.

Yet, I have no idea why on earth the input box for the upload on the website allows for more characters, I guess I'll need to create an Issue over there.

Similarily, SC should not allow for input or copy & paste into the description field to be more than 255 characters.

K

**Comment by peternewman** [comment]
@westnordost it would be much better if the field size was limited to 255 characters, currently this will entirely silently lose information and you'll be none the wiser until someone complains they can't make sense of the note!

Although I appreciate it's better than a stacktrace!

**Comment by matkoniecz** [comment]
That it would turn make impossible to provide description in note about the situation. I thought a bit and I see no obvious improvement here, and this will be likely fairly rare.

(though, if that turns out to be a big problem in practice - opening a new issue would be a good idea)

**Comment by mnalis** [comment]
Is there no way to limit an android input field limit to maximum number of characters (e.g. like [maxlength](https://www.w3schools.com/tags/att_input_maxlength.asp) attribute in HTML)? That would seem to me a better solution than silently truncating note.

**Comment by westnordost** [comment]
The note is not truncated, only the copy&pasted description of the GPX track.

**Comment by matkoniecz** [comment]
> Is there no way to limit an android input field limit to maximum number of characters

There is, and it is used for one of places where user directly enters tag value.

But note text length is not limited and should not be (at least not limited in way impacting normal users).
