### ISSUE TITLE
NullPointerException within MapFragment.onLowMemory causes startup crash

### ISSUE THREAD

**Issue by adrianclay** [streetcomplete/StreetComplete#4221]
**How to Reproduce**

I've been unable to recreate the conditions with an emulator.

Commenting out the line below stops the startup crash from occurring on my physical device.

https://github.com/streetcomplete/StreetComplete/blob/31f2a8a972a74e9743f3d10b113334020bd9ab55/app/src/main/java/de/westnordost/streetcomplete/screens/main/map/MapFragment.kt#L196

**Expected Behavior**
No crash.

**Versions affected**
v45.1, 31f2a8a972a74e9743f3d10b113334020bd9ab55

<details>
<summary>Stack trace</summary>

```
2022-07-18 23:20:15.816 3405-3405/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.westnordost.streetcomplete, PID: 3405
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapzen.tangram.MapController.onLowMemory()' on a null object reference
        at com.mapzen.tangram.MapView.onLowMemory(MapView.java:319)
        at de.westnordost.streetcomplete.screens.main.map.MapFragment.onLowMemory(MapFragment.kt:196)
        at androidx.fragment.app.Fragment.performLowMemory(Fragment.java:3223)
        at androidx.fragment.app.FragmentManager.dispatchLowMemory(FragmentManager.java:3006)
        at androidx.fragment.app.Fragment.performLowMemory(Fragment.java:3224)
        at androidx.fragment.app.FragmentManager.dispatchLowMemory(FragmentManager.java:3006)
        at androidx.fragment.app.FragmentManager.lambda$new$1(FragmentManager.java:454)
        at androidx.fragment.app.FragmentManager.$r8$lambda$OSbytOFWiBhg-JuC-68xxqeOPrI(FragmentManager.java)
        at androidx.fragment.app.FragmentManager$$ExternalSyntheticLambda3.accept(R8$$SyntheticClass)
        at androidx.activity.ComponentActivity.onTrimMemory(ComponentActivity.java:872)
        at android.app.ActivityThread.handleTrimMemory(ActivityThread.java:5294)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1776)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

</details>

**Comment by Helium314** [comment]
Maybe the line should only be called if `isMapInitialized == true`?

**Comment by westnordost** [comment]
This is a bug in tangram-es. Calling `onLowMemory` on the view should never result in a crash, regardless of whether the map view has been initialized or not. So, this should be posted over at tangram-es.

However, given the de-facto development standstill of tangram-es, to additionally add a workaround for this in StreetComplete code is warranted because we don't know if/when it will be fixed in tangram-es. For a proper fix, it should be looked into tangram-es to see what exactly is causing the crash. (After all, it could be that it always crashes on onLowMemory? - for example)
