### ISSUE TITLE
Crash with creating a driving school

### ISSUE THREAD

**Issue by HolgerJeromin** [streetcomplete/StreetComplete#4474]
Describe how to reproduce it here:
Created a new driving school

               Thread: main
       App version: 48.0-alpha1
       Device: motorola  ocean, Android 10
       Locale: de_DE
       Stack trace:
       java.lang.IllegalStateException: Check failed.
at de.westnordost.streetcomplete.screens.main.edithistory.EditHistoryAdapter.onSynced(EditHistoryAdapter.kt:60)
at de.westnordost.streetcomplete.screens.main.edithistory.EditHistoryFragment$editHistoryListener$1$onSynced$1.invokeSuspend(EditHistoryFragment.kt:41)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:241)
at android.app.ActivityThread.main(ActivityThread.java:7604)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@4a8a600, Dispatchers.Main.immediate]

**Comment by FloEdelmann** [comment]
How ironic :smile:

**Comment by Helium314** [comment]
Should be fixed in https://github.com/streetcomplete/StreetComplete/commit/84503c5c72fed915b61353a297e1b49ab412362a

Did you have the edit history open?

**Comment by HolgerJeromin** [comment]
> Did you have the edit history open?

Yeah, I think, yes. Thanks

**Comment by westnordost** [comment]
Though I never fully understood how this could happen in the first place, I just thought that this is not worth crashing over.
