### ISSUE TITLE
SC 53.0 crashes on startup

### ISSUE THREAD

**Issue by mnalis** [streetcomplete/StreetComplete#5030]
After upgrade, app crashes immediately on startup and is unusable.

**How to Reproduce**
- (I did not have any outstanding quests waiting for upload)
- use F-Droid to upgrade to StreetComplete 53.0 (same issue with upgrading to F-droid SCEE 53.0)
- attempt to start StreetComplete
- app crashes immediately without any message
- trying multiple times, as well as rebooting and trying again does not help
- it does not even offer to send crash report on subsequent attempts to start (as those crash immediately)

**Expected Behavior**
- app would start like all previous version did

**Versions affected**
SC 53.0. Phone is Huawei P30 Pro with EMUI 12.0.0 (which should be Android 10)

**Comment by mnalis** [comment]
this is what I find manually in LogCat reader:

```
[05-16 02:22:48.050 5697:5735 E/AndroidRuntime]
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: de.westnordost.streetcomplete.expert, PID: 5697
org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.edithistory.EditHistoryController']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.StreetCompleteApplication$special$$inlined$inject$default$6.invoke(ComponentCallbackExt.kt:131)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at de.westnordost.streetcomplete.StreetCompleteApplication.getEditHistoryController(StreetCompleteApplication.kt:83)
        at de.westnordost.streetcomplete.StreetCompleteApplication.access$getEditHistoryController(StreetCompleteApplication.kt:76)
        at de.westnordost.streetcomplete.StreetCompleteApplication$onCreate$2.invokeSuspend(StreetCompleteApplication.kt:134)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Application), StandaloneCoroutine{Cancelling}@5b3384, Dispatchers.Default]
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.osm.edits.ElementEditsController']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.data.edithistory.EditHistoryModuleKt$editHistoryModule$1$2.invoke(EditHistoryModule.kt:131)
        at de.westnordost.streetcomplete.data.edithistory.EditHistoryModuleKt$editHistoryModule$1$2.invoke(EditHistoryModule.kt:7)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 20 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Factory:'de.westnordost.streetcomplete.data.osm.edits.ElementEditsDao']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.FactoryInstanceFactory.get(FactoryInstanceFactory.kt:38)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
[05-16 02:22:48.050 5697:5735 E/AndroidRuntime]
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$11.invoke(ElementEditsModule.kt:131)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$11.invoke(ElementEditsModule.kt:28)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 32 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.Database']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$3.invoke(ElementEditsModule.kt:131)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$3.invoke(ElementEditsModule.kt:17)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 40 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'io.requery.android.database.sqlite.SQLiteOpenHelper']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$1.invoke(DbModule.kt:131)
        at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$1.invoke(DbModule.kt:8)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 52 more
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: quest_statistics.quest_type (code 1555)
        at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:778)
        at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:764)
        at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
        at io.requery.android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1834)
        at io.requery.android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1719)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelperKt.renameValue(StreetCompleteSQLiteOpenHelper.kt:256)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelperKt.renameQuest(StreetCompleteSQLiteOpenHelper.kt:252)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelperKt.access$renameQuest(StreetCompleteSQLiteOpenHelper.kt:1)

[05-16 02:22:48.050 5697:5735 E/AndroidRuntime]
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.onUpgrade(StreetCompleteSQLiteOpenHelper.kt:218)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:273)
        at io.requery.android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:174)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.<init>(StreetCompleteSQLiteOpenHelper.kt:118)
        at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$2.invoke(DbModule.kt:9)
        at de.westnordost.streetcomplete.data.DbModuleKt$dbModule$1$2.invoke(DbModule.kt:9)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 64 more

[05-16 02:22:48.051 1549:6580 I/DropBoxManagerService]
add tag=data_app_crash isTagEnabled=true flags=0x2

[05-16 02:22:48.052 1549:1980 E/ActivityManager]
do not add repeated dropbox, mLastAppCrashedPid==5697

```

**Comment by mnalis** [comment]
Android `Clear cache` does not help, and I definitely do not want to do `Clear data`, as there are presets and ignore lists that I don't want to lose. And attempting to `Downgrade` APK also fails :sob:

**Comment by Helium314** [comment]
The crash log is actually from SCEE, which you can tell by `Process: de.westnordost.streetcomplete.expert, PID: 5697`, so the line number are different.

But the reason is likely the same:
`SQLiteConstraintException: UNIQUE constraint failed: quest_statistics.quest_type (code 1555)`
when adjusting statistics
`renameValue(EditTypeStatisticsTables.NAME, EditTypeStatisticsTables.Columns.ELEMENT_EDIT_TYPE, old, new)`
as part of renaming a quest
`db.renameQuest("AddPicnicTableCover", "AddAmenityCover")`

I wonder why this doesn't happen for others...
Do you answer many picnic table quests?

If you have root access, rescuing settings / presets, and possibly fixing the crash, should be simple.

**Comment by mnalis** [comment]
> The crash log is actually from SCEE, which you can tell by Process: de.westnordost.streetcomplete.expert, PID: 5697, so the line number are different.

Right, sorry, here is the StreetComplete one:

```
[05-16 14:44:29.162 32401:32436 E/AndroidRuntime]
FATAL EXCEPTION: DefaultDispatcher-worker-4
Process: de.westnordost.streetcomplete, PID: 32401
org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.edithistory.EditHistoryController']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.StreetCompleteApplication$special$$inlined$inject$default$6.invoke(ComponentCallbackExt.kt:131)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at de.westnordost.streetcomplete.StreetCompleteApplication.getEditHistoryController(StreetCompleteApplication.kt:73)
        at de.westnordost.streetcomplete.StreetCompleteApplication.access$getEditHistoryController(StreetCompleteApplication.kt:66)
        at de.westnordost.streetcomplete.StreetCompleteApplication$onCreate$2.invokeSuspend(StreetCompleteApplication.kt:137)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Application), StandaloneCoroutine{Cancelling}@cd51d2c, Dispatchers.Default]
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.osm.osmquests.OsmQuestController']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.data.edithistory.EditHistoryModuleKt$editHistoryModule$1$2.invoke(EditHistoryModule.kt:131)
        at de.westnordost.streetcomplete.data.edithistory.EditHistoryModuleKt$editHistoryModule$1$2.invoke(EditHistoryModule.kt:7)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 20 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [Singleton:'de.westnordost.streetcomplete.data.osm.edits.MapDataWithEditsSource']
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:61)
        at org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:46)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:53)
        at org.koin.core.instance.SingleInstanceFactory$get$1.invoke(SingleInstanceFactory.kt:51)

[05-16 14:44:29.163 32401:32436 E/AndroidRuntime]
        at org.koin.mp.KoinPlatformTools.synchronized(KoinPlatformTools.kt:20)
        at org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:51)
        at org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:111)
        at org.koin.core.scope.Scope.resolveValue(Scope.kt:237)
        at org.koin.core.scope.Scope.resolveInstance(Scope.kt:224)
        at org.koin.core.scope.Scope.get(Scope.kt:205)
        at de.westnordost.streetcomplete.data.osm.osmquests.OsmQuestModuleKt$osmQuestModule$1$4.invoke(OsmQuestModule.kt:131)
        at de.westnordost.streetcomplete.data.osm.osmquests.OsmQuestModuleKt$osmQuestModule$1$4.invoke(OsmQuestModule.kt:11)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 32 more
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: quest_statistics.quest_type (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), (OS error - 2:No such file or directory)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:875)
        at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:776)
        at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:66)
        at android.database.sqlite.SQLiteDatabase.updateWithOnConflict(SQLiteDatabase.java:1785)
        at android.database.sqlite.SQLiteDatabase.update(SQLiteDatabase.java:1726)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelperKt.renameValue(StreetCompleteSQLiteOpenHelper.kt:232)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelperKt.renameQuest(StreetCompleteSQLiteOpenHelper.kt:228)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelperKt.access$renameQuest(StreetCompleteSQLiteOpenHelper.kt:1)
        at de.westnordost.streetcomplete.data.StreetCompleteSQLiteOpenHelper.onUpgrade(StreetCompleteSQLiteOpenHelper.kt:195)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:436)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:332)
        at de.westnordost.streetcomplete.data.AndroidDatabase.getDb(AndroidDatabase.kt:32)
        at de.westnordost.streetcomplete.data.AndroidDatabase.query(AndroidDatabase.kt:74)
        at de.westnordost.streetcomplete.data.Database$DefaultImpls.query$default(Database.kt:24)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsDao.getAllUnsynced(ElementEditsDao.kt:79)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsController.getAllUnsynced(ElementEditsController.kt:40)
        at de.westnordost.streetcomplete.data.osm.edits.MapDataWithEditsSource.rebuildLocalChanges(MapDataWithEditsSource.kt:421)
        at de.westnordost.streetcomplete.data.osm.edits.MapDataWithEditsSource.<init>(MapDataWithEditsSource.kt:211)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$12.invoke(ElementEditsModule.kt:29)
        at de.westnordost.streetcomplete.data.osm.edits.ElementEditsModuleKt$elementEditsModule$1$12.invoke(ElementEditsModule.kt:29)
        at org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:54)
        ... 44 more

[05-16 14:44:29.164 1549:2776 E/ActivityManager]
do not add repeated dropbox, mLastAppCrashedPid==32401

```

The error does look a little different: `Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: quest_statistics.quest_type (Sqlite code 1555 SQLITE_CONSTRAINT_PRIMARYKEY), (OS error - 2:No such file or directory)`, would the reason/fix still be the same?

> I wonder why this doesn't happen for others...
> Do you answer many picnic table quests?

Some, but I'd not say particularly many. [SC statistics](https://www.westnordost.de/streetcomplete/statistics/?user_id=172435) service says `"AddPicnicTableCover":111` altogether.

> If you have root access, rescuing settings / presets, and possibly fixing the crash, should be simple.

Unfortunately not :cry: ; Huawei has stopped issuing bootloader unlock codes before my P30 Pro arrived, and all tutorials I've found seem to depend on that, and so I'm stuck without root (if anyone does know how to root it with recent EMUI, I'd be grateful!)

Any chance the issue can be fixed in code so after next upgrade (or signed beta or whatever) the SC(EE) autorecovers?

**Comment by Helium314** [comment]
I just had a look at the `EditTypeStatisticsTables`, and the edit name is the primary key.
It appears that you had `AddAmenityCover` in the database before the upgrade to SC 53.0. As part of this upgrade, `AddPicnicTableCover` is renamed to `AddAmenityCover`, which fails because the name must be unique.

My guess is that you used some other version of SC 53.0 and answered an `AddAmenityCover` quest, then used actual SC 52.1. Here the statistics were synced and you had both the old and the new name in the database, hence the crash.

@westnordost does the statistics table actually need the quest rename? As fast as I understand statistics are downloaded again anyway and overwrite the local statistics.

**Comment by westnordost** [comment]
Uhh, I guess not. The quest name is aliased for the statistics anyway, no?

**Comment by mnalis** [comment]
> @mnalis Here I removed the line causing the crash: https://github.com/Helium314/SCEE/actions/runs/4995266712
Does it work for you?

Yup, that version starts up normally, thanks! Hopefully the fix can be added in StreetComplete too
