### ISSUE TITLE
Crash after switching between overlay and about Fragment

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5049]
**How to Reproduce**
- Open StreetComplete -> select overlay with ability to create new nodes (street parking, adress or shops)
- After select overlay, select + to create new node
- select burger menu -> About
- Rotate screen -> Go back to map -> app crashed (crash is present if i access to profil Fragment or other fragment)

**Expected Behavior**
- New node form is present on map in landscape mode

**Versions affected**
Android 13 - v53.0

Stack trace:
```
java.lang.NullPointerException
at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.getGeometry(AbstractOverlayForm.kt:126)
at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.get_countryInfo(AbstractOverlayForm.kt:89)
at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.getCountryInfo(AbstractOverlayForm.kt:95)
at
de.westnordost.streetcomplete.overlays.address.AddressOverlayForm.onViewCreated(AddressOverlayForm.kt:154)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3137)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2890)
at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3138)
at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1435)
at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2979)
at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2897)
at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
at de.westnordost.streetcomplete.screens.MainActivity.onStart(MainActivity.kt:182)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
at android.app.Activity.performStart(Activity.java:8366)
at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3666)
at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:224)
at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:204)
at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:61)
at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:5738)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2313)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by westnordost** [comment]
Hm, cannot reproduce. But the stack trace may help.

What about keeping a quest form open? Does it crash too? What about an overlay form (that does not create a new node)?

**Comment by Jean-BaptisteC** [comment]
No problem with quest form open and overlay form open (overlay without ability to create new node)

**Comment by westnordost** [comment]
Ah, nevermind. Nothing of that sort. When a new node is created, its geo position is calculated from the position of the crosshair on the map. This is done on `onViewCreated`. However, if the activity just re-created after being destroyed, the map is not even initialized yet. Henve, the geo position is null.

**Comment by westnordost** [comment]
Maybe it is high time we used view models in this project...
