### ISSUE TITLE
Crash with adding addresses via overlay

### ISSUE THREAD

**Issue by Cj-Malone** [streetcomplete/StreetComplete#5054]
In the process of adding a bunch of [addresses](https://www.openstreetmap.org/changeset/136905561), in offline mode, I could repeatedly crash SCEE when trying to add addresses nodes (to buildings/entrances) on a couple of specific buildings, the majority worked perfectly.

**How to Reproduce**
After I got home (with network access?) (and uploaded?), I can no longer reproduce. But when I was out I couldn't add an address node to [here](https://www.openstreetmap.org/way/457234885). (I tried multiple times and ended up adding the address to the entire building fine)

I also couldn't add [no 6](https://www.openstreetmap.org/node/10948930558) to the building, but [8](https://www.openstreetmap.org/node/10948977641) worked fine.

Again with [48](https://www.openstreetmap.org/node/10948980529), when I was out I assumed I had passed out of the bbox of downloaded data, but now it's obvious I added addresses in every direction around it in the same session.

<details>

<summary>Stack trace</summary>

```
                Thread: main
        App version: 53.0
        Device: google  sunfish, Android 13
        Locale: en_GB
        Stack trace:
        java.lang.NullPointerException
	at de.westnordost.streetcomplete.overlays.address.AddressOverlayForm$initCreatingPointOnWay$2.invoke(AddressOverlayForm.kt:191)
	at de.westnordost.streetcomplete.overlays.address.AddressOverlayForm$initCreatingPointOnWay$2.invoke(AddressOverlayForm.kt:190)
	at kotlin.sequences.TransformingSequence$iterator$1.next(Sequences.kt:210)
	at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
	at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
	at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
	at kotlin.sequences.SequencesKt.toList(Unknown Source:0)
	at de.westnordost.streetcomplete.overlays.address.AddressOverlayForm.initCreatingPointOnWay(AddressOverlayForm.kt:194)
	at de.westnordost.streetcomplete.overlays.address.AddressOverlayForm.access$initCreatingPointOnWay(AddressOverlayForm.kt:53)
	at de.westnordost.streetcomplete.overlays.address.AddressOverlayForm$onViewCreated$$inlined$doOnLayout$1.onLayoutChange(View.kt:132)
	at android.view.View.layout(View.java:23734)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1891)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1729)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1638)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:799)
	at android.view.View.layout(View.java:23716)
	at android.view.ViewGroup.layout(ViewGroup.java:6413)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4093)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3434)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2346)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9190)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
	at android.view.Choreographer.doFrame(Choreographer.java:832)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7903)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)


        Last log before crash:
        2023-06-03 13:38:45.743 I MapDataController: Fetched 1071 elements and geometries in 10ms
2023-06-03 13:38:43.256 I MainFragment: closeBottomSheet while showing null
2023-06-03 13:38:43.239 I MainFragment: edited: AddressOverlay
2023-06-03 13:38:43.239 I EditHistoryController: history: add edit AddressOverlay for []
2023-06-03 13:38:43.238 I OsmQuestController: Persisted 0 new and removed 0 already resolved quests in 0.0s
2023-06-03 13:38:43.238 I OsmQuestController: Created 0 quests for 1 updated elements in 0.2s
2023-06-03 13:38:43.149 I MapDataController: Fetched 116 elements and geometries in 1ms
2023-06-03 13:38:43.147 D OsmQuestController: AddEntrance requires surrounding map data to determine applicability to NODE#-789
2023-06-03 13:38:43.039 I MapDataWithEditsSource: updated: [NODE -789], deleted: []
2023-06-03 13:38:43.031 I AbstractOverlayForm: solve AddressOverlay for null, extra: false
2023-06-03 13:38:40.627 I MapDataController: Fetched 771 elements and geometries in 18ms
2023-06-03 13:38:29.532 I MapDataController: Fetched 1029 elements and geometries in 22ms
2023-06-03 13:38:29.528 W SpatialCache: bbox does not align with tiles, clearing incomplete tiles from cache
2023-06-03 13:38:21.001 I MapDataController: Fetched 4043 elements and geometries in 111ms
2023-06-03 13:38:20.729 I MapDataController: Fetched 1596 elements and geometries in 39ms
2023-06-03 13:38:20.721 W SpatialCache: bbox does not align with tiles, clearing incomplete tiles from cache
2023-06-03 13:38:14.900 I MapDataController: Fetched 2074 elements and geometries in 46ms
2023-06-03 13:38:09.282 I MapDataController: Fetched 2401 elements and geometries in 13ms
2023-06-03 13:38:09.278 I MainFragment: onResume
2023-06-03 13:38:09.258 I MainFragment: onStart (add listeners)
2023-06-03 13:38:07.676 I MainFragment: onSaveInstanceState
2023-06-03 13:38:07.674 I MainFragment: onStop (remove listeners)
2023-06-03 13:38:07.018 I MainFragment: onPause
2023-06-03 13:38:06.387 I Preloader: Preloading data took 0.7s
2023-06-03 13:38:06.387 I Preloader: Loaded features dictionary in 0.7s
2023-06-03 13:38:06.332 I MapDataController: Fetched 2401 elements and geometries in 152ms
2023-06-03 13:38:05.968 I Preloader: Loaded country boundaries in 0.3s
2023-06-03 13:38:05.690 I MainFragment: onResume
2023-06-03 13:38:04.828 I MainFragment: onStart (add listeners)
2023-06-03 13:38:04.812 I MainFragment: onViewStateRestored
2023-06-03 13:38:04.775 I MainFragment: onViewCreated
2023-06-03 13:38:04.742 I MainFragment: onCreateView
2023-06-03 13:38:04.736 I MainFragment: onCreate
2023-06-03 13:38:04.732 I MainFragment: onAttach

        Log warnings and errors:
        2023-06-03 13:38:20.721 W SpatialCache: bbox does not align with tiles, clearing incomplete tiles from cache
2023-06-03 13:38:29.528 W SpatialCache: bbox does not align with tiles, clearing incomplete tiles from cache

        MapDataWithEditsSource listeners:
        [de.westnordost.streetcomplete.data.osm.osmquests.OsmQuestController$mapDataSourceListener$1@cdc9561, MainFragment{5cb03aa} (322235e8-de6a-458d-8c1e-9aadff5105bf id=0x7f090202), de.westnordost.streetcomplete.screens.main.map.StyleableOverlayManager$mapDataListener$1@9755886]
```

</details>

I have 8 stack traces, if needed.

**Versions affected**
53.0 **SCEE** (But I'm assuming it's an issue here, cc @Helium314)

**Comment by matkoniecz** [comment]
> SCEE

Can you check is it happening with StreetComplete? You can install both SC and SCEE at the same time

**Comment by Cj-Malone** [comment]
No. I can no longer reproduce in SCEE. Possibly related to changing the OSM data, or downloading more data.

**Comment by Helium314** [comment]
The line where it crashes is `val positions = way.nodeIds.map { data.getNode(it)!!.position }`, means the node isn't found.
I assume it's fixed by #5026/#5040.

Do you know whether you edited a node of a nearby building before?

**Comment by Helium314** [comment]
> No. I can no longer reproduce at all. Possibly related to changing the OSM data, or downloading more data.

If my suspicion is correct, you will not be able to reproduce it once you uploaded your answers.

**Comment by Cj-Malone** [comment]
> Do you know whether you edited a node of a nearby building before?

"Edited" I absolutely added nodes to ways nearby. And I probably edited existing ones.
"Nearby" in the first example I had just added an address to a nearby building, but it's different way. In the second example I had just added an address to the same way.
The third example is a little weirder, it's further away from other changes, I can't remember if I tried to add 41 to the building after, or didn't even try before turning back.

> If my suspicion is correct, you will not be able to reproduce it once you uploaded your answers.

Sorry everyone. I did intend to make this before uploading, but I forgot.

**Comment by Helium314** [comment]
> "Nearby"

Details: When clicking the plus button, data within 100 m of the crosshair is loaded. If a building is only partially inside this box, still all nodes are loaded.
If you edited (not added) a node that is part of this parially-inside-building, but outside the 100 m box you will get the crash.

> Sorry everyone. I did intend to make this before uploading, but I forgot.

If the crashes are gone after uploading that's actually good, because then I'm quite confident that the issue is already fixed. You can try SCEE 53.2, which includes this fix.

**Comment by Cj-Malone** [comment]
Awesome thanks. I can now reproduce in SC 53, but not in SCEE 53.2. So this is solved already :)

I actually saw 53.2 before I went out, but didn't update for some reason. I could have skipped this whole thing :p
