### ISSUE TITLE
Crash when trying to add address in overlay mode

### ISSUE THREAD

**Issue by deevroman** [streetcomplete/StreetComplete#5177]
**How to Reproduce**
1. Turn on address overlay
2. Tilt the map
3. Tap +
4. Crash

https://github.com/streetcomplete/StreetComplete/assets/25708359/c60f9dd1-4534-4ca5-bbb0-97d1f653c5ad

**Versions affected**
StreetComplete 53.3 Android 13 OneUI 5.1 Samsung Galaxy A52

**Comment by westnordost** [comment]
Does it only crash if you tilt the map? You use the Google Play version of the app?

**Comment by deevroman** [comment]
> Does it only crash if you tilt the map?

I've occasionally encountered a crash when enabling the overlay, but I can't reproduce it.

> You use the Google Play version of the app?

Yes

**Comment by westnordost** [comment]
>> You use the Google Play version of the app?

> Yes. If logs are needed, I can use adb

The stack trace would be most helpful

**Comment by westnordost** [comment]
Can reproduce

```
FATAL EXCEPTION: main
Process: de.westnordost.streetcomplete.debug, PID: 22946
java.lang.NullPointerException
	at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.getGeometry(AbstractOverlayForm.kt:126)
	at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.get_countryInfo(AbstractOverlayForm.kt:89)
	at de.westnordost.streetcomplete.overlays.AbstractOverlayForm.getCountryInfo(AbstractOverlayForm.kt:95)
	at de.westnordost.streetcomplete.overlays.address.AddressOverlayForm.onViewCreated(AddressOverlayForm.kt:154)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3147)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:588)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:272)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1943)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1839)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1782)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:565)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```
For the country's locale, the form needs to know the geo-position of wherever the crosshair is pointing. Tangram-es however returns null, i.e. it can for one reason or another not determine the position of where the crosshais is pointing at...

So, I am not sure how we can workaround that. The geo-position is necessary to show the form (and to place the new address, after all). If it is not available... and the overlay form fragment has to be already opened because it contains the crosshair, i.e. the screen position that should be translated to the geo-position.

**Comment by Helium314** [comment]
For me the crash happens only very close to the maximum allowed tilt.
Maybe maximum tilt could be slightly reduced as a workaround?

**Comment by westnordost** [comment]
Does it happen for you only at almost maximum allowed tilt, @deevroman ?

**Comment by deevroman** [comment]
Indeed, if you return the tilt quite a bit after the maximum tilt, there is no crash.

**Comment by westnordost** [comment]
What would you estimate, percentage-wise. How much do you have to return it?

**Comment by deevroman** [comment]
Very little. I'll put it another way: if there is no shaking of the map at the end of the tilt, then there is no crash.

**Comment by Helium314** [comment]
Crashes with tilt `PI / 6  + 0.15`, works with tilt `PI / 6 + 0.1`.

**Comment by westnordost** [comment]
Looks like a good workaround for me then.
