### ISSUE TITLE
org.koin.core.error.NoBeanDefFoundException: No definition found for class:'java.util.concurrent.FutureTask' q:' & qualifier:'getFeature''. Check your definitions!

### ISSUE THREAD

**Issue by matkoniecz** [streetcomplete/StreetComplete#5309]
maybe I broke something in my setup but I tried standard solutions already like running clean, reinstalling Android Studio, clearing caches, resetting repository and so on

happens with 922f5c62f18bdf68e683273ae58ad71f7f11d8b0 - will try `git bisect` to find when it started to happen

```
Unable to download
                                                                                                    org.koin.core.error.NoBeanDefFoundException: No definition found for class:'java.util.concurrent.FutureTask' q:' & qualifier:'getFeature''. Check your definitions!
                                                                                                    	at org.koin.core.scope.Scope.throwDefinitionNotFound(Scope.kt:304)
                                                                                                    	at org.koin.core.scope.Scope.resolveValue(Scope.kt:274)
                                                                                                    	at org.koin.core.scope.Scope.resolveInstance(Scope.kt:231)
                                                                                                    	at org.koin.core.scope.Scope.get(Scope.kt:210)
                                                                                                    	at de.westnordost.streetcomplete.quests.QuestsModuleKt$questsModule$1$3$2.invoke(QuestsModule.kt:133)
                                                                                                    	at de.westnordost.streetcomplete.quests.QuestsModuleKt$questsModule$1$3$2.invoke(QuestsModule.kt:196)
                                                                                                    	at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHours.hasFeatureName(AddOpeningHours.kt:192)
                                                                                                    	at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHours.hasName(AddOpeningHours.kt:187)
                                                                                                    	at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHours.isApplicableTo(AddOpeningHours.kt:148)
                                                                                                    	at de.westnordost.streetcomplete.quests.opening_hours.AddOpeningHours.getApplicableElements(AddOpeningHours.kt:142)
                                                                                                    	at de.westnordost.streetcomplete.data.osm.osmquests.OsmQuestController$createQuestsForBBox$deferredQuests$1$1.invokeSuspend(OsmQuestController.kt:172)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by westnordost** [comment]
> org.koin.core.error.NoBeanDefFoundException: No definition found for class:'java.util.concurrent.FutureTask' q:' & qualifier:'getFeature''. Check your definitions!

The line in question is

```kotlin
                get<FutureTask<FeatureDictionary>>(named("FeatureDictionaryFuture"))
                    .get().getFeature(tags)

```

... I am confused by this error message. Is it not finding the `FutureTask<FeatureDictionary>` or does the `FutureTask` retrieved for some reason not contain a `FeatureDictionary` and because of this, it does not find a method named `getFeature` on it?`

Since currently you seem to be the only one that can reproduce this issue, try taking this statement apart into several lines of code and set breakpoints.

**Comment by westnordost** [comment]
So, where you able to solve it?

**Comment by matkoniecz** [comment]
yes, somehow it stopped happening on its own
