### ISSUE TITLE
Crash when I share position to other app and rotate screen

### ISSUE THREAD

**Issue by Jean-BaptisteC** [streetcomplete/StreetComplete#5334]
**How to Reproduce**
- Open StreetComplete
- Doing long press on screen
- Use feature open position to another app
- Wait Android Share Menu is opened and rotate device
- App crashed
```FATAL EXCEPTION: main
Process: system:ui, PID: 5121
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.internal.app.ResolverListAdapter$ViewHolder.bindLabel(java.lang.CharSequence, java.lang.CharSequence, boolean)' on a null object reference
at com.android.internal.app.ResolverListAdapter.onBindView(ResolverListAdapter.java:659)
at com.android.internal.app.ResolverListAdapter.getView(ResolverListAdapter.java:627)
at android.widget.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:224)
at android.widget.AbsListView.obtainView(AbsListView.java:2466)
at android.widget.ListView.measureHeightOfChildren(ListView.java:1415)
at android.widget.ListView.onMeasure(ListView.java:1321)
at android.view.View.measure(View.java:27122)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
at android.view.View.measure(View.java:27122)
at com.android.internal.widget.ViewPager.onMeasure(ViewPager.java:1455)
at com.android.internal.app.ResolverViewPager.onMeasure(ResolverViewPager.java:55)
at android.view.View.measure(View.java:27122)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27122)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27122)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27122)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
at com.android.internal.widget.ResolverDrawerLayout.onMeasure(ResolverDrawerLayout.java:996)
at android.view.View.measure(View.java:27122)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27122)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27122)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7008)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:750)
at android.view.View.measure(View.java:27122)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4182)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2759)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3086)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2465)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9305)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1339)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1348)
at android.view.Choreographer.doCallbacks(Choreographer.java:952)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1322)
at android.os.Handler.handleCallback(Handler.java:958)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8177)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Expected Behavior**
Android share menu stay opened

**Versions affected**
v55.0 on Android 14

**Comment by Helium314** [comment]
The stack trace doesn't contain a line of StreetComplete, so I suspect it _might_ be an Android issue. Does rotating with the share menu open work when using (location) share functionality from other apps?

**Comment by mnalis** [comment]
works fine in `v54.12` on my Android 10 (EMUI 12.0.0):

https://github.com/streetcomplete/StreetComplete/assets/156656/ae987f2e-292a-4c00-a302-b5469d0ae4f5

**Comment by Jean-BaptisteC** [comment]
Yes you right reproduced with Google Photos
I close this issue

**Comment by matkoniecz** [comment]
Thanks for checking!

**Comment by Jean-BaptisteC** [comment]
Crash is fixed with december Android 14 update
