### ISSUE TITLE
Uploading stops every few (<20) quests and prompts to re-authenticate against OSM

### ISSUE THREAD

**Issue by esilja** [streetcomplete/StreetComplete#5532]
**How to Reproduce**
Unclear. I'm pressing the upload button (autoupload is disabled), I had like 200 quests ready to upload. At least every twenty or so quests, the uploading stops and I get the "You need to authorize with your OSM user account to publish your answers. Authorize now? You can also do this later on the profile screen" dialog.

This also happens repeatedly. Sometimes, my user name ends up being "null" (not entirely sure on the exact name). I can then log out and log in with my actual user account again.

**Expected Behavior**
All quest answers are getting uploaded.

**Versions affected**
I believe I was already using this version successfully for the past month or so, without hitting this issue.

StreetComplete 56.1 from F-Droid.
Android 13
LineageOS 20-20240215-microG-sunfish

**adb**
```
03-11 21:02:40.786 12660 22464 I Upload  : Starting upload
03-11 21:02:40.800 12660 22464 D TrafficStats: tagSocket(96) with statsTag=0xffffffff, statsUid=-1
03-11 21:02:41.236 12660 22464 I ChangesetManager: Created changeset #148521254
03-11 21:02:41.331 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:41.511 12660 22464 I ChangesetManager: Created changeset #148521256
03-11 21:02:41.604 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:41.762 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:42.119 12660 22464 I ChangesetManager: Created changeset #148521257
03-11 21:02:42.224 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:42.387 12660 22464 I ChangesetManager: Created changeset #148521258
03-11 21:02:42.531 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:42.957 12660 22464 I ChangesetManager: Created changeset #148521259
03-11 21:02:43.089 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:43.501 12660 22464 I ChangesetManager: Created changeset #148521260
03-11 21:02:43.591 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:43.971 12660 22464 I ChangesetManager: Created changeset #148521261
03-11 21:02:44.099 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:44.480 12660 22464 I ChangesetManager: Created changeset #148521263
03-11 21:02:44.611 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:44.771 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:44.890 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:45.029 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:45.194 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:45.506 12660 22464 I ChangesetManager: Created changeset #148521265
03-11 21:02:45.598 12660 22464 D ElementEditsUploader: Uploaded a CreateNodeAction
03-11 21:02:45.627 12660 22545 D OsmQuestController: AddEntrance requires surrounding map data to determine applicability to NODE#11717554372
03-11 21:02:45.628 12660 22545 I MapDataController: Fetched 138 elements and geometries in 0ms
03-11 21:02:45.629 12660 20672 D OsmQuestController: AddLevel requires surrounding map data to determine applicability to NODE#11717554372
03-11 21:02:45.632 12660 22464 D OsmQuestController: Created AddSeating for NODE#11717554372
03-11 21:02:45.633 12660 22464 D OsmQuestController: Created AddAirConditioning for NODE#11717554372
03-11 21:02:45.633 12660 22464 D OsmQuestController: Created AddSmoking for NODE#11717554372
03-11 21:02:45.633 12660 22464 D OsmQuestController: Created AddVegetarian for NODE#11717554372
03-11 21:02:45.633 12660 22464 D OsmQuestController: Created AddHalal for NODE#11717554372
03-11 21:02:45.634 12660 22464 D OsmQuestController: Created AddKosher for NODE#11717554372
03-11 21:02:45.635 12660 22464 D OsmQuestController: Created AddWheelchairAccessBusiness for NODE#11717554372
03-11 21:02:45.635 12660 22464 D OsmQuestController: Created AddAcceptsCards for NODE#11717554372
03-11 21:02:45.811 12660 22464 I OsmQuestController: Created 8 quests for 1 updated elements in 0.2s
03-11 21:02:45.818 12660 22464 I OsmQuestController: Persisted 8 new and removed 8 already resolved quests in 0.0s
03-11 21:02:45.947 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:46.115 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:46.428 12660 22464 I ChangesetManager: Created changeset #148521266
03-11 21:02:46.563 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:46.985 12660 22464 I ChangesetManager: Created changeset #148521267
03-11 21:02:47.080 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:47.516 12660 22464 I ChangesetManager: Created changeset #148521268
03-11 21:02:47.652 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:47.820 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:48.030 12660 12670 I .streetcomplete: Background young concurrent copying GC freed 2379073(80MB) AllocSpace objects, 157(5136KB) LOS objects, 56% free, 65MB/149MB, paused 253us,88us total 179.763ms
03-11 21:02:48.030 12660 12670 W .streetcomplete: Reducing the number of considered missed Gc histogram windows from 193 to 100
03-11 21:02:48.155 12660 12660 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (22498) crash detected (code -1).
03-11 21:02:48.163 12660 22464 I ChangesetManager: Created changeset #148521269
03-11 21:02:48.260 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:48.412 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:48.573 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:48.726 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:48.880 12660 22464 D ElementEditsUploader: Uploaded a UpdateElementTagsAction
03-11 21:02:49.022 12660 22464 E Upload  : Unable to upload
03-11 21:02:49.022 12660 22464 E Upload  : de.westnordost.streetcomplete.data.user.AuthorizationException
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.openChangeset(Unknown Source:89)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.changesets.OpenChangesetsManager.createChangeset(Unknown Source:17)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.uploadChanges(Unknown Source:12)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditUploader.upload(Unknown Source:67)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.uploadEdit(Unknown Source:98)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader.access$uploadEdit(Unknown Source:0)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$1.invokeSuspend(Unknown Source:34)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$1.invoke(SourceFile:0)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1$1.invoke(SourceFile:0)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Unknown Source:7)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Unknown Source:53)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source:0)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.edits.upload.ElementEditsUploader$upload$2$1.invokeSuspend(Unknown Source:66)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:98)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:0)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(Unknown Source:14)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Unknown Source:28)
03-11 21:02:49.022 12660 22464 E Upload  : 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Unknown Source:0)
03-11 21:02:49.022 12660 22464 E Upload  : Caused by: de.westnordost.osmapi.common.errors.OsmAuthorizationException: Forbidden (403) - <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
03-11 21:02:49.022 12660 22464 E Upload  : <html><head>
03-11 21:02:49.022 12660 22464 E Upload  : <title>403 Forbidden</title>
03-11 21:02:49.022 12660 22464 E Upload  : </head><body>
03-11 21:02:49.022 12660 22464 E Upload  : <h1>Forbidden</h1>
03-11 21:02:49.022 12660 22464 E Upload  : <p>You don't have permission to access this resource.</p>
03-11 21:02:49.022 12660 22464 E Upload  : <hr>
03-11 21:02:49.022 12660 22464 E Upload  : <address>Apache/2.4.54 (Ubuntu) Server at api.openstreetmap.org Port 443</address>
03-11 21:02:49.022 12660 22464 E Upload  : </body></html>
03-11 21:02:49.022 12660 22464 E Upload  : 
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.osmapi.OsmApiErrorFactory.createError(Unknown Source:73)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.osmapi.OsmConnection.handleResponseCode(Unknown Source:21)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.osmapi.OsmConnection.makeRequest(SourceFile:0)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.osmapi.OsmConnection.makeAuthenticatedRequest(SourceFile:0)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.osmapi.map.MapDataApi.openChangeset(Unknown Source:15)
03-11 21:02:49.022 12660 22464 E Upload  : 	at de.westnordost.streetcomplete.data.osm.mapdata.MapDataApiImpl.openChangeset(Unknown Source:7)
03-11 21:02:49.022 12660 22464 E Upload  : 	... 20 more
03-11 21:02:49.043 12660 12682 W Parcel  : Expecting binder but got null!
03-11 21:02:49.058 12660 12682 E OpenGLRenderer: Unable to match the desired swap behavior.
```

**Comment by Helium314** [comment]
Actually that might be some issue with OSM. I remember a few hours ago I wasn't able to open the website, maybe there are still some hiccups.

**Comment by esilja** [comment]
Do the quest answers get lost btw?

**Comment by Helium314** [comment]
Most likely not, as the upload is not successful

**Comment by mnalis** [comment]
> Do the quest answers get lost btw?

Answers should be safe IMHO, but you can make sure  by looking at https://www.openstreetmap.org/user/YOURUSERNAME/history yourself (and replacing `YOURUSERNAME` with your actual username) and see if those previous batches got uploaded successfully.

First I though if that might perhaps be related to rate limits for new users (e.g. https://community.openstreetmap.org/t/the-new-rate-limiting-prevents-participants-to-missing-maps-mapathons-from-saving-buildings/106610) but if you've been actively using the account for more than a month then it is somewhat unlikely...

> 03-11 21:02:48.030 12660 12670 I .streetcomplete: Background young concurrent copying GC freed 2379073(80MB) AllocSpace objects, 157(5136KB) LOS objects, 56% free, 65MB/149MB, paused 253us,88us total 179.763ms
03-11 21:02:48.030 12660 12670 W .streetcomplete: Reducing the number of considered missed Gc histogram windows from 193 to 100
03-11 21:02:48.155 12660 12660 E chromium: [ERROR:aw_browser_terminator.cc(154)] Renderer process (22498) crash detected (code -1).

I wonder if that garbage collection being triggered just before the error might have something to do with it? I seem to recall some other discussions lately where android could remove and reinstate activities resulting in broken data flow; could something like that be possibly happening here in the middle of the upload?

**Comment by westnordost** [comment]
I am quite sure this must have been a hiccup with the OSM API. See also this forum post from today: https://community.openstreetmap.org/t/forbidden-beim-klick-auf-eine-note/110413

StreetComplete force-logs-out the user when the OSM API responds with HTTP Error code 403 (Forbidden) or 401 (Unauthorized) since it assumes that something is wrong with the user's login.

Your edits are safe. Edits are only deleted from your device after they have been _successfully_ uploaded.

Can you confirm that this does not happen anymore?

**Comment by esilja** [comment]
I'm not able to confirm that this doesn't happen anymore, I upgraded to 57.0 via F-Droid, which crashes due to #5522. AFAIK, you cannot downgrade Android apps, so I can't go back to 56.1. I also can't upgrade to 57.1 in my understanding because I'd need a 57.1 signed by F-Droid.

This means I'll have to wait until 57.1 is released by F-Droid to test this again.

**Comment by westnordost** [comment]
OK, can't be long till it hits F-Droid

**Comment by matkoniecz** [comment]
> prompts to re-authenticate against OSM

see also https://community.openstreetmap.org/t/what-is-normal-login-cookie-duration/110452/2

> I imagine you’re asking this because you got logged out yesterday and the reason that happened is that we were subject to a DOS attack which caused a lot of sessions to be created which in turn caused the session store to overflow and evict older sessions.

**Comment by esilja** [comment]
>> I imagine you’re asking this because you got logged out yesterday and the reason that happened is that we were subject to a DOS attack which caused a lot of sessions to be created which in turn caused the session store to overflow and evict older sessions.

Interestingly, I was still logged in in the browser session, so I only had to click "authenticate", not enter my password again

**Comment by westnordost** [comment]
sc 57.1 is on f-droid since yesterday

**Comment by westnordost** [comment]
Anyway, will close this as the source of the issue was clear and the behavior of StreetComplete is fine.

**Comment by esilja** [comment]
Sorry. It also did not appear again. :)
